@startuml
title Диаграмма контекста АБС

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(manager, "Менеджер бэк-офиса", "")
System(abs, "Автоматизированная банковская система (АБС)", "Delphi client + Oracle")

System_Ext(internet_bank, "Интернет-банк", "")
System_Ext(site, "Сайт", "")
System_Ext(sms_gateway, "СМС-шлюз", "СМС-шлюз телеком-оператора")
System_Ext(call_center, "Система колл-центра (CRM)", "")

Rel(manager, abs, "Использует АБС")
Rel(internet_bank, abs, "Запрашивает депозиты и персональные ставки (раз в сутки)")
Rel(internet_bank, abs, "Проведение платежей, открытие текущих счетов")
Rel(site, abs, "Запрашивает депозиты и ставки (раз в сутки)")
Rel(call_center, abs, "Отправляет заявки на депозит с сайта")
Rel(abs, sms_gateway, "Отправляет СМС-сообщения клиентам")
Rel(abs, internet_bank, "Читает сообщения с заявками на депозит")
Rel(abs, internet_bank, "Отправляет сообщения с изменениями остатков на счетах")

@enduml